mysite/blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list'),
    path('about/',views.AboutView.as_view(),name='about'),
    path('post/(?P<pk>\d+)',views.PostDetailView.as_view(),name='post_detail'),
    path('post/new/',views.CreatePostView.as_view(),name='post_new'),
    path('post/(?P<pk>\d+)/edit/',views.PostUpdateView.as_view(),name='post_edit'),
    path('drafts/',views.DraftListView.as_view(),name='post_draft_list'),
    path('post/(?P<pk>\d+)/remove/',views.PostDeleteView.as_view(),name='post_remove'),
    path('post/(?P<pk>\d+)/publish/',views.post_publish,name='post_publish'),
    path('post/(?P<pk>\d+)/comment/',views.add_comment_to_post,name='add_comment_to_post'),
    path('comments/(?P<pk>\d+)/approve/',views.comment_approve,name='comment_approve'),
    path('comment/(?P<pk>\d+)/remove/',views.comment_remove,name='comment_remove'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('accounts/login/',views.LoginView.as_view(),name='login'),
    path('accounts/logout/',views.LogoutView.as_view(),name='logout',kwargs={'next_page':'/'})

]

mysite/blog/models.py
from django.db import models
# IMPORT TIMEZONE
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth import authenticate, login

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now())
    published_date = models.DateTimeField(blank=True,null=True)


    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("blog:post_detail",kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments',on_delete=models.CASCADE,default='')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now())
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_list')

    def __str__(self):
        return self.text

mysite/blog/forms.py
from django import forms
from .models import Post,Comment

class PostForm(forms.ModelForm):
# "editable medium-editor-textarea" class is used to edit the content in the text area while writing a post or comment. It can be used to make the text bold, italic, underline, and can be converted to h1, h2 and so on....
    class Meta():
        model = Post
        fields = ('author','title','text')
        widgets = {
        'title': forms.TextInput(attrs={'class':'textinputclass'}),
        'text': forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }

class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('author','text')
        widgets = {
        'author': forms.TextInput(attrs={'class':'textinputclass'}),
        'text': forms.Textarea(attrs={'class':'editable medium-editor-textarea'})

        }

mysite/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from blog.forms import PostForm,CommentForm
from blog.models import Post,Comment
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView,ListView,DetailView,
                                        CreateView,UpdateView,DeleteView)


# Create your views here.

# 1. For ABOUT ME PAGE
class AboutView(TemplateView):
    template_name = 'about.html'

# 2. List all the approved posts here. This is also our Landing Page
class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    # lte - less than or equal to

# 3. To view the details of the post such as its content, comments.
class PostDetailView(DetailView):
    model = Post

# 4.  To create a new post
class CreatePostView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model=Post

# 5. To edit or delete the published posts by the superuser
class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model=Post

# 6. To delete a post by the superuser
class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

# 6. After a post is created it is saved into drafts so that it can be approved or disapproved by the superuser.
class DraftListView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('-created_date')

##############################################################
####################################################
# 7. To publish a post
def post_publish(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect('blog:post_detail',pk=pk)

# 8. To add comment to a post
@login_required
def add_comment_to_post(request,pk):
    post  = get_object_or_404(Post,pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail',pk=pk)

    else:
        form = CommentForm()
    return render(request,'blog/comment_form.html',{'form':form})

@login_required
def comment_approve(request,pk):
    comment  = get_object_or_404(Comment,pk=pk)
    comment.approve()
    return redirect('blog:post_detail',pk=comment.post.pk)

@login_required
def comment_remove(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail',pk=post_pk)

mysite/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
<h1>About me</h1>
<p>Thanks for Visiting</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

{% endblock %}

mysite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Blog</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Medium style Editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&family=Russo+One&display=swap" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>
    <!-- NAVIGATION -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-expand{-sm|-md|-lg|-xl}">
      <a class="navbar-brand" href="{% url 'blog:post_list' %}">My blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
 </button>
 <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active"><a class="nav-link"href="{% url 'blog:about' %}">About</a></li>
        <li class="nav-item active"><a class="nav-link"href="https://github.com/Shrey1501">Github</a></li>
        <li class="nav-item active"><a class="nav-link"href="https://www.linkedin.com/in/shreygurehiya/">Linkedin</a></li>
      </ul>
</div>
<div class="collapse navbar-collapse" id="navbarNav">
      <ul class="nav justify-content-end">
        {% if user.is_authenticated %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:post_new' %}">New Post</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:post_draft_list' %}">Drafts</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link">Welcome: {{user.username}}</a>
        </li>
        {% else %}
        <li ><a class="nav justify-content-end" href="{% url 'login' %}"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
  <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
  <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
</svg></a></li>
        {% endif %}

      </ul>
    </div>
    </nav>

    <!-- CONTENT BLOCK -->
    <div class="content container">
      <div class="row">
        <div class="col-md-8">
          <div class="blog_posts">
            {% block content %}

            {% endblock %}

          </div>

        </div>

      </div>

    </div>

    <!-- SCRIPT FOR RESPONSIVE PAGES -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  </body>
</html>

mysite/blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% block content %}
<h1>New Comment</h1>
<form class="post-form"  method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="btn btn-default" name="button">Post Comment</button>
  </form>
  <script>
    var editor = new MediumEditor('.editable');
  </script>
{% endblock %}

mysite/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}
 <form  method="post">
   {% csrf_token %}
   <p>Are you sure you want to delete? {{object}}</p>
   <input type="submit" class="btn btn-danger " name="" value="Confirm">
 </form>
{% endblock %}

mysite/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}

  <h1 class="posttitle">{{post.title}}</h1>
  {% if post.published_date %}
    <div class="date postdate">
      {{post.published_date}}
      </div>
  {% else %}
    <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>

  {% endif %}

  <p class="postcontent">{{ post.text|safe|linebreaksbr }}</p>

  {% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}">
      <span class="glyphicon glyphicon-pencil"></span>
    </a>
    <a class="btn btn-primary" href="{% url 'blog:post_remove' pk=post.pk %}">
      <span class="glyphicon glyphicon-remove"></span>
    </a>
  {% endif %}

  <hr>
  <a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment</a>

  <div class="container">
    {% for comment in post.comments.all %}
    <br>
      {% if user.is_authenticated or comment.approved_comment %}
        {{comment.created_date}}
          {% if not comment.approved_comment %}
          <a class="btn btn-primary" href="{% url 'blog:comment_remove' pk=comment.pk %}">
            <span class="glyphicon glyphicon-remove"></span>
          </a>
          <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}">
            <span class="glyphicon glyphicon-ok"></span>
          </a>
          {% endif %}
          <p>{{comment.text|safe|linebreaksbr}}</p>
          <p>Posted By: {{comment.author}}</p>
      {% endif %}
      {% empty %}
      <p>No Comments.</p>
    {% endfor %}
  </div>
<br>

{% endblock %}

mysite/blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}
{% block content %}
{% for post in posts %}
<div class="post">
  <p class="date">created: {{ post.created_date|date:'d-m-y' }}</p>
  <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
  <p>{{post.text|truncatechars:200}}</p>
</div>
{% endfor %}
{% endblock %}

mysite/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% block content %}
<h1>New Post</h1>
<form class="post-form" method="POST">
  {% csrf_token %}
  {{ form.as_p}}
  <button type="submit" class=" save btn btn-default">Save</button>

</form>
<script>
  var editor = new MediumEditor('.editable');

</script>
{% endblock %}

mysite/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="centerstage">
  {% for post in post_list %}
  <div class="post">
    <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
    <div class="date">
      <p>Published on: {{post.published_date|date:"d/m/y"}}</p>
    </div>
    <p>Comments: {{ post.approve_comments.count }}</p>

  </div>
  {% endfor %}

</div>
{% endblock %}